"""Story unit (mini-arc) data model - 3-7 chapter narrative arcs within volumes"""

from __future__ import annotations

from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field


class StoryUnit(BaseModel):
    """Mini-arc structure: 3-7 chapters with setup -> escalation -> climax -> resolution

    Each volume is divided into multiple StoryUnits, each spanning 3-7 chapters
    and representing a complete narrative arc with its own conflict and resolution.

    Example::

        unit = StoryUnit(
            volume_id=1,
            name="新生试炼篇",
            chapters=[1, 2, 3, 4, 5],
            hook="主角被卷入试炼场",
            escalation_point=3,
            turning_point=4,
            closure_method="主角险胜试炼",
            residual_question="试炼背后的黑手是谁？",
        )
    """

    arc_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="UUID",
    )
    volume_id: int = Field(..., ge=1, description="Parent volume number")
    name: str = Field(
        ..., min_length=1, max_length=100, description="Arc name (e.g., '新生试炼篇')"
    )
    chapters: list[int] = Field(
        ..., min_length=3, max_length=7, description="Chapters in this arc"
    )

    # Arc structure
    phase: Literal["setup", "escalation", "climax", "resolution"] = Field(
        "setup", description="Current phase of the arc"
    )

    # Key beats
    hook: str = Field(..., min_length=1, description="Opening hook that launches the arc")
    escalation_point: int = Field(
        ..., ge=1, description="Chapter where tension peaks"
    )
    turning_point: int = Field(
        ..., ge=1, description="Chapter where direction changes"
    )
    closure_method: str = Field(
        ..., min_length=1, description="How the arc resolves"
    )
    residual_question: str = Field(
        ..., min_length=1, description="Unresolved element that hooks into next arc"
    )

    # Metadata
    status: Literal["planning", "in_progress", "completed"] = Field(
        "planning", description="Arc completion status"
    )
    completion_rate: float = Field(
        0.0, ge=0.0, le=1.0, description="0.0-1.0, chapters completed / total chapters"
    )

    def __repr__(self) -> str:
        return (
            f"StoryUnit(arc_id={self.arc_id!r}, name={self.name!r}, "
            f"chapters={self.chapters}, phase={self.phase!r}, "
            f"status={self.status!r}, completion_rate={self.completion_rate})"
        )

    def __str__(self) -> str:
        return f"[{self.status}] {self.name} (ch.{self.chapters[0]}-{self.chapters[-1]}, {self.phase})"


class ArcBrief(BaseModel):
    """Planning brief for a story arc - generated by NovelDirector

    Contains the conflict structure, stakes, and beat plan for a single arc.

    Example::

        brief = ArcBrief(
            arc_id="abc-123",
            central_conflict="主角与师门叛徒的对决",
            protagonist_goal="找回被盗的宗门秘宝",
            success_consequence="宗门地位稳固",
            failure_consequence="宗门面临解散危机",
            climax_description="主角在绝境中觉醒隐藏血脉",
            resolution_outcome="秘宝夺回，叛徒逃走留下伏笔",
        )
    """

    arc_id: str = Field(..., description="Reference to parent StoryUnit")

    # Core conflict
    central_conflict: str = Field(
        ..., min_length=1, description="Main conflict for this arc"
    )
    protagonist_goal: str = Field(
        ..., min_length=1, description="What protagonist wants in this arc"
    )
    antagonist_goal: str = Field(
        "", description="What antagonist wants (if applicable)"
    )

    # Stakes
    success_consequence: str = Field(
        ..., min_length=1, description="What happens if protagonist succeeds"
    )
    failure_consequence: str = Field(
        ..., min_length=1, description="What happens if protagonist fails"
    )

    # Structure
    setup_beats: list[str] = Field(
        default_factory=list, description="Key beats in setup phase"
    )
    escalation_beats: list[str] = Field(
        default_factory=list, description="Key beats in escalation phase"
    )
    climax_description: str = Field(
        ..., min_length=1, description="How the climax unfolds"
    )
    resolution_outcome: str = Field(
        ..., min_length=1, description="Arc resolution result"
    )
